### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by ansarimohammed422** [MahmoudRH/RoomXML#6]
I am glad that you added support for material you

But its in the light mode

Would be better if it switches to dark mode when dark mode of the system is enabled

Or support system dark mode etc

**Comment by MahmoudRH** [comment]
Sure, I'll add it soon

**Comment by MahmoudRH** [comment]
Added in [v2.0.0](https://github.com/MahmoudRH/D_Note/releases/tag/v2.0.0)
